---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy html file for site
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package (ubuntu)
    tags: samba
    package:
      name: samba
      state: latest

