---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
       user: simone
       key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOe7gZmO/vWe8RwBmWUAnOEc6g92RxDwrzZVwOVc5p93 ansiblessh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOe7gZmO/vWe8RwBmWUAnOEc6g92RxDwrzZVwOVc5p93 ansible"

- hosts: workstations
  become: true
  tasks:

   - name: install unzip
     package:
       name: unzip

   - name: install terraform
     unarchive:
       src: https://releases.hashicorp.com/terraform/1.7.4/terraform_1.7.4_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root


- hosts: all
  become: true
  pre_tasks:

   - name: update repository index (Ubuntu)
     tags: always
     apt:
       update_cache: yes
     changed_when: false
     when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
     - base

- hosts: workstations
  become: true
  roles:
     - workstations

- hosts: web_servers
  become: true
  roles:
     - web_servers

- hosts: db_servers
  become: true
  roles:
     - db_servers

- hosts: file_servers
  become: true
  roles:
     - file_servers


